name: Composite Action Example

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "My environment variable"

    steps:
      - name: Test
        env:
          STEP_MY_VAR: "My step environment variable"
        run: |
          echo "Value: $MY_VAR"
          echo "Value: $STEP_MY_VAR"
          echo "Value: ${{ vars.REPO_VAR }}"

      - name: Secret
        run: |
          echo "Secret value: ${{ secrets.MY_SECRET }}"
