name: Test Composite action

on: [pull_request]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ls
        uses: ./actions/my-action
        with:
          message: "Oscar"
