name: Hello World

on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello, world!"

      - name: Touch File
        run: touch hola.txt

      - name: Set Text
        run: echo "Hello, world!" > hola.txt

      - name: Read File
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -la
